name: Build pipeline
on:
  push:
    branches: [ main ]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y build-essential cmake libx11-dev libxrandr-dev libgl1-mesa-dev libudev-dev libfreetype6-dev libopenal-dev libflac-dev libvorbis-dev
    - name: Build SFML from source
      run: |
        git clone https://github.com/SFML/SFML.git
        cd SFML
        git checkout main
        cmake .
        make
        sudo make install
    - name: Build my project
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build . --config Release
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: linux-build
        path: build/Release/myproject