name: Build pipeline
on:
  push:
    branches: [ main ]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update -y && apt-get upgrade -y
        sudo apt-get install -y build-essential cmake libx11-dev libxrandr-dev libgl1-mesa-dev libudev-dev libfreetype6-dev libopenal-dev libflac-dev libvorbis-dev
    - name: Build my project
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build . --config Release
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: linux-build
        path: build/Release/lambdalogic